
export interface CityCardProps {
    temperature: string;
    weather?: string;
    lat: number;
    long: number;
    city: string;
    state: string;
}

export interface HourlyWeatherCardProps {
    iconPath: string;
    hour: string;
    temperature: number;
}

export interface CityInfoProps {
    name: string;
    coord: Coord,
    countryCode: string,
    temperature: number,
    maxTemperature: number,
    minTemperature: number,
    weather: Weather[] | [],
}

export interface UserLocation {
    latitude: number;
    longitude: number;
}

// Generated by https://quicktype.io
export interface DailyWeatherResponse {
    cod: string;
    message: number;
    cnt: number;
    list: List[];
    city: City;
}

export interface City {
    id: number;
    name: string;
    coord: Coord;
    country: string;
    population: number;
    timezone: number;
    sunrise: number;
    sunset: number;
}

export interface Coord {
    lat: number;
    lon: number;
}

export interface List {
    dt: number;
    main: MainClass;
    weather: Weather[];
    clouds: Clouds;
    wind: Wind;
    visibility: number;
    pop: number;
    sys: Sys;
    dt_txt: string;
    rain?: Rain;
}

export interface MainClass {
    temp: number;
    feels_like: number;
    temp_min: number;
    temp_max: number;
    pressure: number;
    sea_level: number;
    grnd_level: number;
    humidity: number;
    temp_kf: number;
}

export interface Rain {
    '3h': number;
}

export interface Sys {
    pod: Pod;
}

export enum Pod {
    D = 'd',
    N = 'n',
}

export enum Description {
    BrokenClouds = 'broken clouds',
    ClearSky = 'clear sky',
    FewClouds = 'few clouds',
    LightRain = 'light rain',
    OvercastClouds = 'overcast clouds',
    ScatteredClouds = 'scattered clouds',
}

export enum MainEnum {
    Clear = 'Clear',
    Clouds = 'Clouds',
    Rain = 'Rain',
}


// Generated by https://quicktype.io

export interface WeatherResponse {
    coord: Coord;
    weather: Weather[];
    base: string;
    main: Main;
    visibility: number;
    wind: Wind;
    clouds: Clouds;
    dt: number;
    sys: Sys;
    timezone: number;
    id: number;
    name: string;
    cod: number;
}

export interface Clouds {
    all: number;
}

export interface Main {
    temp: number;
    feels_like: number;
    temp_min: number;
    temp_max: number;
    pressure: number;
    humidity: number;
    sea_level: number;
    grnd_level: number;
}

export interface Sys {
    country: string;
    sunrise: number;
    sunset: number;
}

export interface Weather {
    id: number;
    main: string;
    description: string;
    icon: string;
}

export interface Wind {
    speed: number;
    deg: number;
    gust: number;
}
